title: Vembadi Govardhan # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Undergraduate student in India, passionate about Machine Learning, Deep Learning, and MLOps. Working on significant projects in the ML domain. Committed to continuous learning and seeking opportunities to apply my skills in real-world teams.
  <br>
  <a href="https://www.linkedin.com/in/govardhan-vembadi-ba916724a/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="govardhanv" height="20" width="20" style=""/></a>
  <a href="https://www.github.com/Govardhan211103/" target="blank"><img align="center" src="https://cdn-icons-png.flaticon.com/512/25/25231.png" alt="govardhan___v" height="25" width="25" style="filter: grayscale(100%); padding-left:10px" /></a>
  <a href="https://www.instagram.com/govardhan____v/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/instagram.svg" alt="govardhan___v" height="20" width="20" style=" padding-left:10px" /></a>


  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
