title: Vembadi Govardhan # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
  Undergraduate student in India, passionate about Machine Learning, Deep Learning, and MLOps. Currently engaged in significant projects that showcase my expertise in the ML domain. Committed to continuous learning and seeking opportunities to apply my skills in real-world teams.
  <br><br>
  <a href="https://www.linkedin.com/in/govardhan-vembadi/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
