title: Vembadi Govardhan # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>
   Undergraduate student in India, passionate about Machine Learning, Deep Learning, and MLOps. Working on significant projects in the ML domain. Seeking opportunities to apply my skills within real-world teams.
  <br><br>
  <a href="https://www.linkedin.com/in/govardhan-vembadi/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="govardhan" height="25" width="25" style=""/></a>
  <a href="https://www.github.com/govardhanvembadi/" target="blank"><img align="center" src="https://cdn-icons-png.flaticon.com/512/25/25231.png" alt="govardhan" height="25" width="25" style="filter: grayscale(100%); padding-left:15px" /></a>
  <a href="https://govardhan211103.medium.com/" target="blank"><img align="center" src="https://cdn.icon-icons.com/icons2/2997/PNG/512/medium_logo_icon_187624.png" alt="govardhan" height="25" width="25" style="filter: grayscale(100%); padding-left:15px" /></a>
  <a href="https://www.instagram.com/govardhan____v/" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/instagram.svg" alt="govardhan" height="25" width="25" style=" padding-left:15px" /></a>


  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
